name: laco_ifsc_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.6.0
  firebase_storage: ^13.4.3
  # State
  provider: ^6.1.2
  # Location & Maps
  geolocator: ^14.0.3
  google_maps_flutter: ^2.9.0
  geocoding: ^4.0.0
  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  # Animacao
  lottie: ^3.1.2
  # HTTP
  http: ^1.2.1
  # Utils
  intl: ^0.20.3
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  share_plus: ^13.2.0
  google_fonts: ^8.1.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - .env
