// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MOCK-WEB-KEY-12345',
    appId: '1:1234567890:web:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'laco-ifsc-mobile',
    authDomain: 'laco-ifsc-mobile.firebaseapp.com',
    storageBucket: 'laco-ifsc-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EWTMb0x55sjQ225HIQJBKFvJYt0RXsw',
    appId: '1:510383029326:android:8f92703677b464fba2d71f',
    messagingSenderId: '510383029326',
    projectId: 'lacomobileapp',
    storageBucket: 'lacomobileapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERnQFczGYeuc92YyTi7J6YiUyVidAlEg',
    appId: '1:510383029326:ios:c0b5ddd0d2eeee04a2d71f',
    messagingSenderId: '510383029326',
    projectId: 'lacomobileapp',
    storageBucket: 'lacomobileapp.firebasestorage.app',
    iosClientId: '510383029326-3ct67s9ei8tmq9ggfbtumb8lknc7catg.apps.googleusercontent.com',
    iosBundleId: 'com.example.lacoIfscMobile',
  );
}
